apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: machwave-worker-prod
spec:
  template:
    spec:
      template:
        spec:
          serviceAccountName: machwave-api-prod@machwave.iam.gserviceaccount.com
          maxRetries: 1
          timeoutSeconds: 3600
          containers:
            - image: IMAGE_PLACEHOLDER
              env:
                - name: GCP_PROJECT_ID
                  value: machwave
                - name: GCS_BUCKET_NAME
                  value: machwave-data-prod
                - name: FIREBASE_PROJECT_ID
                  value: machwave-76f5f
              resources:
                limits:
                  cpu: "2"
                  memory: 2Gi
