apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: machwave-api-prod
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      serviceAccountName: machwave-api-prod@machwave.iam.gserviceaccount.com
      containers:
        - image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          env:
            - name: GCP_PROJECT_ID
              value: machwave
            - name: GCS_BUCKET_NAME
              value: machwave-data-prod
            - name: FIREBASE_PROJECT_ID
              value: machwave-76f5f
            - name: CORS_ORIGINS
              value: https://machwave.app
            - name: CLOUD_RUN_JOB_NAME
              value: machwave-worker-prod
            - name: CLOUD_RUN_JOB_REGION
              value: us-central1
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
